version: "3"
services:
  nginx:
    ports:
      - "3000:80"
      
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=lucas
      - MONGO_PASSWORD=mypass
      - SESSION_SECRET=secret

    command: yarn run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lucas
      - MONGO_INITDB_ROOT_PASSWORD=mypass
